// JTG Blueprint Registry Catalog
// Central registry of all available extensions and their package locations.
// Keys generated by the registry reference extensions listed here.

export const EXTENSIONS = [
  {
    id: "hello-jtg",
    name: "Hello JTG",
    version: "1.0.0",
    description:
      "Official example extension demonstrating the JTG Blueprint lifecycle, backend API routing, database migrations, configuration, and UI integration.",
    icon: "Sparkles",
    category: "utilities",
    tags: ["example", "demo", "starter", "blueprint"],
    author: {
      name: "JTG Core Team",
      email: "team@jtgpanel.com",
      url: "https://github.com/kiragamingofficial95-cmd",
    },
    license: "MIT",
    repository: "https://github.com/kiragamingofficial95-cmd/JTG-PANEL-UPGRADATION-CREDITS-TO-KIRA-GAMING",
    homepage: "https://blue-print-jtg-panel.vercel.app/extensions/hello-jtg",
    compatibility: { jtg_panel: ">=2.0.0", blueprint: ">=1.0.0" },
    permissions: ["servers.read", "settings.read"],
    packageFile: "packages/hello-jtg-1.0.0.zip",
    downloads: 0,
    rating: 0,
    reviews: 0,
    releaseDate: "2026-01-01T00:00:00.000Z",
    status: "published",
  },
];

export function findExtension(id) {
  return EXTENSIONS.find((e) => e.id === id) || null;
}

export function getPublicExtensionList() {
  return EXTENSIONS.map((e) => ({
    id: e.id,
    name: e.name,
    version: e.version,
    description: e.description,
    icon: e.icon,
    tags: e.tags || [],
    author: e.author,
    category: e.category,
    downloads: e.downloads || 0,
    rating: e.rating || 0,
    status: e.status || "published",
  }));
}

export function getPublicExtensionDetail(id) {
  const e = findExtension(id);
  if (!e) return null;
  return {
    id: e.id,
    name: e.name,
    version: e.version,
    description: e.description,
    icon: e.icon,
    tags: e.tags || [],
    author: e.author,
    category: e.category,
    license: e.license,
    repository: e.repository,
    homepage: e.homepage,
    compatibility: e.compatibility,
    permissions: e.permissions || [],
    downloads: e.downloads || 0,
    rating: e.rating || 0,
    reviews: e.reviews || 0,
    releaseDate: e.releaseDate,
    status: e.status || "published",
  };
}
